clear; clc;
%% User Input:
nRuns = 1;                      %number of Bin Packing Problems to solve
nItems = 400;                   %number of items in each problem
mipGap = 0.10;                  %When Gurobi can terminate early
BPParray = [];                  %filename for presampled BPP instances

policiesToRun=["greedy" ...     % list of policies to run for the subproblem. either 'greedy', 'exact', or a filename
               ];


%% Program
if isempty(BPParray)
    BPPinstances = cell(1);
    for i = 1:nRuns
        [n, C, w] = BPPrandomInstance(1000, nItems);
        BPPinstance.n = n;
        BPPinstance.C = C;
        BPPinstance.w = w;
        BPPinstances{i} = BPPinstance;
    end
else
    load('BPParray')
end

nPolicies = numel(policiesToRun);
results = dictionary(policiesToRun, struct);
for run = 1:nRuns
    fprintf('Commencing run number %d:\n', run)
    n = BPPinstances{run}.n;
    C = BPPinstances{run}.C;
    w = BPPinstances{run}.w;
    for policyCell = policiesToRun
        policy = policyCell{1};
        fprintf('\nRunning policy from %s: \n',policy)
        if strcmp(policy, 'greedy')
            [nExactCalled, exactTime, heurTime, nTotal, time] = columnGenerationSolver(n, C, w, 'greedy', [], 1, 1, mipGap);
        elseif strcmp(policy, 'gurobiHeur')
            [nExactCalled, exactTime, heurTime, nTotal, time] = columnGenerationSolver(n, C, w, 'exactHeur');
        elseif strcmp(policy, 'exact')
            [nExactCalled, exactTime, heurTime, nTotal, time] = columnGenerationSolver(n, C, w, 'exact');
        else
            [nExactCalled, exactTime, heurTime, nTotal, time] = columnGenerationSolver(n, C, w, "piPrime", policy, 1, 1, mipGap);
        end
        results(policy).nExactCalled(run) = nExactCalled;
        results(policy).exactTime(run)    = exactTime;
        results(policy).nTotal(run)       = nTotal;
        results(policy).time(run)         = time;
        results(policy).heurTime(run)     = heurTime;
    end
end
for i = 1:numel(policiesToRun)
    fprintf('Evaluating policy: '+policiesToRun(i)+'\n')
    fprintf(['Number of columns generated by Binary Programming: %f \n' ...
        'Number of columns generated by the heuristic: %f \n' ...
        'Total number of columns generated: %f \n' ...
        'Time spent in Binary Programming: %f \n' ...
        'Time spent in the heuristic: %f \n' ...
        'Total Time spent: %f \n\n'],[sum(results(policiesToRun(i)).nExactCalled)/nRuns, sum(results(policiesToRun(i)).nTotal - results(policiesToRun(i)).nExactCalled)/nRuns, sum(results(policiesToRun(i)).nTotal)/nRuns , sum(results(policiesToRun(i)).exactTime)/nRuns, sum(results(policiesToRun(i)).heurTime)/nRuns, sum(results(policiesToRun(i)).time)/nRuns])
end

%save('BPPinstancesArray', "BPPinstances")
